<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTSndazx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTSndazx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTSndazx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTSndazx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTSndazx\App_KernelProdContainer([
    'container.build_hash' => 'TSndazx',
    'container.build_id' => '3f1ce41a',
    'container.build_time' => 1600255810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTSndazx');
